<script src="<?php echo base_url();?>assets/frontend_asset/js/jquery-1.12.1.min.js"></script>
    <!-- popper js -->
    <script src="<?php echo base_url();?>assets/frontend_asset/js/popper.min.js"></script>
    <!-- bootstrap js -->
    <script src="<?php echo base_url();?>assets/frontend_asset/js/bootstrap.min.js"></script>
    <!-- easing js -->
    <script src="<?php echo base_url();?>assets/frontend_asset/js/jquery.magnific-popup.js"></script>
    <!-- swiper js -->
    <script src="<?php echo base_url();?>assets/frontend_asset/js/swiper.min.js"></script>
    <script src="<?php echo base_url();?>assets/frontend_asset/js/wow.min.js"></script>
    <script src="<?php echo base_url();?>assets/frontend_asset/js/jquery.smooth-scroll.min.js"></script>
    <!-- swiper js -->
    <script src="<?php echo base_url();?>assets/frontend_asset/js/masonry.pkgd.js"></script>
    <!-- particles js -->
    <script src="<?php echo base_url();?>assets/frontend_asset/js/owl.carousel.min.js"></script>
    <script src="<?php echo base_url();?>assets/frontend_asset/js/jquery.nice-select.min.js"></script>
    <!-- swiper js -->
    <script src="<?php echo base_url();?>assets/frontend_asset/js/slick.min.js"></script>
    <script src="<?php echo base_url();?>assets/frontend_asset/js/jquery.counterup.min.js"></script>
    <script src="<?php echo base_url();?>assets/frontend_asset/js/waypoints.min.js"></script>
    <!-- contact js -->
    <script src="<?php echo base_url();?>assets/frontend_asset/js/jquery.ajaxchimp.min.js"></script>
    <script src="<?php echo base_url();?>assets/frontend_asset/js/jquery.form.js"></script>
    <script src="<?php echo base_url();?>assets/frontend_asset/js/jquery.validate.min.js"></script>
    <script src="<?php echo base_url();?>assets/frontend_asset/js/mail-script.js"></script>
    <script src="<?php echo base_url();?>assets/frontend_asset/js/contact.js"></script>
    <!-- custom js -->
    <script src="<?php echo base_url();?>assets/frontend_asset/js/custom.js"></script>